name: DockerBuild And Deploy

on:
  push:
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Aliyun
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou
          username: ${{ secrets.REGISTRYUSERNAME }}
          password: ${{ secrets.REGISTRYPASSWORD }}
          
      -
        name: Build and Push
        env:
          IMAGE_TAG: ${{ github.branch }}-${{ github.sha }}
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 -t registry.cn-hangzhou.aliyuncs.com/toodo/blog:$IMAGE_TAG . --push
    
